esphome:
  name: spabad-balboa
  friendly_name: Spabad Balboa

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf

wifi:
  ssid: "Karmskogs_IoT"
  password: "TeleCaster"

api:

ota:
  platform: esphome

logger:

uart:
  - id: uart_bus
    tx_pin: GPIO16
    rx_pin: GPIO17
    baud_rate: 115200

external_components:
  - source:
      type: git
      url: https://github.com/plandai/esp-balboa-spa
    components: [ balboa ]

balboa:
  id: my_balboa
  uart_id: uart_bus
  flow_control_pin: GPIO21

climate:
  - platform: balboa
    name: "Spabad Temperatur"

binary_sensor:
  - platform: balboa
    circ_pump:
      name: "Cirkulationspump"
    pump_1:
      name: "Massagepump 1"
    light:
      name: "Belysning"
    heater:
      name: "Värmare"
